function plotspace(x,y,z)
% Input: interval vector x,y
% Output: plot_3d
    for i=1:length(x)
        x1 = x(i).inf;  x2 = x(i).sup;
        y1 = y(i).inf;  y2 = y(i).sup;
        z1 = z(i).inf;  z2 = z(i).sup;
    
        % 8个顶点分别为：
        % 与(0,0,0)相邻的4个顶点
        % 与(a,b,c)相邻的4个顶点
        V = [x1 y1 z1;...
            x2 y1 z1;...
            x1 y2 z1;...
            x1 y1 z2;...
            x2 y2 z2;...
             x1 y2 z2;...
             x2 y1 z2;...
             x2 y2 z1];
        % 6个面
        % 以(x1,y1,x3)为顶点的三个面
        % 以(x2,y2,z2)为顶点的三个面
        F = [1,2,7,4;...
            1 3 6 4;...
            1 2 8 3;...
             5 8 3 6;...
             5 7 2 8;...
             5 6 4 7];
    
        patch('Faces',F,'Vertices',V,'FaceColor','white',...
              'LineWidth',0.5,'EdgeColor','black');
    end
    view(30,30);
    grid on;
end