figure;
%leg= leg + servo_attach_B;
fill3(attach_B(1,:),attach_B(2,:),attach_B(3,:),'-');
hold on
grid on
new_attachP=Arm+attach_B;
fill3(new_attachP(1,:),new_attachP(2,:),new_attachP(3,:),'-g');
%axis([ -r_B-servo_arm_length, r_B+servo_arm_length,...
%       -r_B-servo_arm_length, r_B+servo_arm_length,...
%       -servo_arm_length rod_length+servo_arm_length]r;
rotate3d on;



for i=1:6
    line([attach_B(1,i) new_attachP(1,i)],... 
         [attach_B(2,i) new_attachP(2,i)],...
         [attach_B(3,i) new_attachP(3,i)],...
         'Color','b','LineWidth',2);

%     line([joint_B(1,i) leg(1,i)],... 
%          [joint_B(2,i) leg(2,i)],...
%          [joint_B(3,i) leg(3,i)],...
%          'Color','k');
%      
%     line([servo_attach_B(1,i) leg(1,i)],... 
%          [servo_attach_B(2,i) leg(2,i)],...
%          [servo_attach_B(3,i) leg(3,i)],...
%          'Color','y');
end
